---
title: "Final Project"
author: "Grant Williams"
date: "2023-11-13"
output: html_document
---

```{r}

# Import Libraries

library(tidyverse)
library(dplyr)
library(foreign)
library(ggplot2)
library(MASS)
library(Hmisc)
library(reshape2)

#Formatting From 2022 Data

# data <- read_csv('data_2022.csv')
# data <- data %>% filter((!pid7 %in% c(4,8,9))) # dropped moderate and not sure
# data <- data %>% mutate(age = 2022 - birthyr)
# data <- data %>% rename(media = CC22_200_1)
# data <- data %>% select(age, gender4,educ,race,pid7,inputstate,region,media,urbancity,pew_religimp,religpew,faminc_new,child18,sexuality)
# 1 is yes, #2 is no 
```

```{r}

# Clean up data_smol
data_smol <- read.csv("data_smol.csv")

# Get rid of state
data_smol <- data_smol[-6]

#Recoding variables of interest from numbers
data_smol <- data_smol %>%
  mutate(gender4 = case_when(gender4 == '1' ~ 'Man',
                             gender4 == '2' ~ 'Woman',
                             gender4 == '3' ~ 'Other',
                             gender4 == '4' ~ 'Other')) %>%
  mutate(race = recode(race,
                       '1' = 'White',
                       '2' = 'Black',
                       '3' = 'Hispanic',
                       '4' = 'Asian',
                       '5' = 'Native American',
                       '6' = 'Two or more races',
                       '7' = 'Other',
                       '8' = 'Native American')) %>%
  mutate(region = recode(region,
                         '1' = 'Northeast',
                         '2' = 'Midwest',
                         '3' = 'South',
                         '4' = 'West')) %>%
  mutate(educ = factor(recode(educ,
                                 '1' = 'No HS',
                                 '2' = 'HS Graduate',
                                 '3' = 'Some College',
                                 '4' = '2-year',
                                 '5' = '4-year',
                                 '6' = 'Post Grad'), 
                          #after recoding assign levels
                          levels = c(
                            'No HS',
                            'HS Graduate',
                            'Some College',
                            '2-year',
                            '4-year',
                            'Post Grad')))%>%
  mutate(pid7 = as.character(pid7)) %>%
  mutate(pid7 = factor(
    recode(pid7,
      '1' = 'Strong Democrat',
      '2' = 'Not Very Strong Democrat',
      '3' = 'Lean Democrat',
      '5' = 'Lean Republican',
      '6' = 'Not very Strong Republican',
      '7' = 'Strong Republican'),
    #After recoding, we assign the order here
    levels = c(
      'Strong Democrat',
      'Not Very Strong Democrat',
      'Lean Democrat',
      'Lean Republican',
      'Not very Strong Republican',
      'Strong Republican'
    )))%>%
mutate(urbancity = recode(urbancity,
                         '1' = 'City',
                         '2' = 'Suburb',
                         '3' = 'Town',
                         '4' = 'Rural area', 
                         '5' = 'Other'))%>%
mutate(pew_religimp= recode(pew_religimp,
                         '1' = 'Very important ',
                         '2' = 'Somewhat important',
                         '3' = 'Not too important',
                         '4' = 'Not at all important'))%>%
mutate(sexuality= recode(sexuality,
                         '1' = ' Heterosexual / straight',
                         '2' = 'Lesbian / gay woman',
                         '3' = 'Gay man',
                         '4' = 'Bisexual',
                         '5'='Other', 
                         '6'='Prefer not to say'))%>%
mutate(religpew = recode(religpew,
                           '1' = 'Protestant',
                           '2' = 'Roman Catholic',
                           '3' = 'Mormon',
                           '4' = 'Eastern or Greek Orthodox',
                           '5' = 'Jewish',
                           '6' = 'Muslim',
                           '7' = 'Buddhist',
                           '8' = 'Hindu',
                           '9' = 'Atheist',
                           '10' = 'Agnostic',
                           '11' = 'Nothing in particular',
                           '12' = 'Something else'))%>%
mutate(faminc_new=recode(faminc_new,
                      "1" = "Less than $10,000",
                      "2" = "$10,000 - $19,999",
                      "3" = "$20,000 - $29,999",
                      "4" = "$30,000 - $39,999",
                      "5" = "$40,000 - $49,999",
                      "6" = "$50,000 - $59,999",
                      "7" = "$60,000 - $69,999",
                      "8" = "$70,000 - $89,999",
                      "9" = "$80,000 - $99,999",
                      "10" = "$100,000 - $119,999",
                      "11" = "$120,000 - $149,999",
                      "12" = "$150,000 - $199,999",
                      "13" = "$200,000 - $249,999",
                      "14" = "$250,000 - $349,999",
                      "15" = "$350,000 - $499,999",
                      "16" = "$500,000 or more",
                      "97" = "Prefer not to say")) %>%
  mutate(faminc_new = factor(faminc_new, levels = c(
    "Less than $10,000",
    "$10,000 - $19,999",
    "$20,000 - $29,999",
    "$30,000 - $39,999",
    "$40,000 - $49,999",
    "$50,000 - $59,999",
    "$60,000 - $69,999",
    "$70,000 - $89,999",
    "$80,000 - $99,999",
    "$100,000 - $119,999",
    "$120,000 - $149,999",
    "$150,000 - $199,999",
    "$200,000 - $249,999",
    "$250,000 - $349,999",
    "$350,000 - $499,999",
    "$500,000 or more",
    "Prefer not to say"
  ))) %>%
  mutate(media = ifelse(media == 1, 1, 0)) %>%
  mutate(child18 = ifelse(child18 == 1, 1, 0)) 
```

```{r}

# How many NAs do we have 

rows_with_na <- data_smol[which(rowSums(is.na(data_smol)) > 0),]

data_smol <- na.omit(data_smol)

```

```{r}
#Plot the data_smol values

library(cowplot)

# Function to create bar plots for categorical variables using ggplot2
plot_categorical_ggplot <- function(data, col) {
  ggplot(data, aes(x = factor(data[[col]]))) +
    geom_bar(fill = "skyblue", color = "black") +
    labs(title = col, x = "") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, size = 5, hjust = 1))
}

# Create a list of ggplot objects
plots_list <- lapply(names(data_smol)[-which(names(data_smol) == "age")], function(col) {
  plot_categorical_ggplot(data_smol, col)
})

# Combine the plots into a grid
plot_grid(plotlist = plots_list, ncol = 6)

```

```{r}

#Age 

ggplot(data_smol, aes(x = age)) +
    geom_histogram(fill = "skyblue", color = "black") +
    labs(title = "Histogram of Age in Non-NA rows", x = "") +
    theme_minimal() 

ggplot(rows_with_na, aes(x = age)) +
    geom_histogram(fill = "skyblue", color = "black") +
    labs(title = "Histogram of Age in NA rows", x = "") +
    theme_minimal() 

```

```{r}

#Plot the rows_with_na values


# Create a list of ggplot objects
plots_list <- lapply(names(rows_with_na)[-which(names(rows_with_na) == "age")], function(col) {
  plot_categorical_ggplot(rows_with_na, col)
})

# Combine the plots into a grid
plot_grid(plotlist = plots_list, ncol = 6)


```

```{r}

# Bar Plot

names <- colnames(data_smol)

for (i in 1:length(names(data_smol))) {
  plot <- ggplot(data_smol, aes(x = !!sym(names(data_smol)[i]), fill = pid7)) +
    geom_bar(position = "fill", stat = "count") +
    labs(title = paste("Spread of Political Leanings by", names(data_smol)[i]),
         x = names(data_smol)[i],
         y = "Proportion") +
    scale_fill_manual(values = rev(c("darkred",  "red1", "lightcoral", "lightblue", "cornflowerblue", "darkblue")),
                      name = "Political Party",
                      labels = c('Strong Democrat', 'Not Very Strong Democrat', 'Lean Democrat',
                                 'Lean Republican', 'Not Very Strong Republican', 'Strong Republican')) +
    theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = .5))
  
  print(plot)
  }


```

AMELIA SECTION

```{r}

# Bar Plot: Gender Distribution Across Political Parties with Flipped Colors
ggplot(data_smol, aes(x = gender4, fill = pid7)) +
  geom_bar(position = "fill", stat = "count") +
  labs(title = " Spread of Political Leanings by Gender",
       x = "Gender",
       y = "Proportion") +
  scale_fill_manual(values = rev(c("darkred", "lightcoral", "indianred1", "lightblue", "cornflowerblue", "darkblue")),
                    name = "Political Party",
                    labels = c('Strong Democrat', 'Not Very Strong Democrat', 'Lean Democrat',
                               'Lean Republican', 'Not Very Strong Republican', 'Strong Republican')) +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5))  # Adjust the angle for better readability

```

```{r}
#Baseline gender model:
gender4_model<- polr(pid7 ~ gender4, data = data_smol, Hess=TRUE)
#store summary
summary_gender4_model<-summary(gender4_model)
# store table
(ctable_baseline_gender <- coef(summary(gender4_model)))
## calculate and store p values
baseline_gender_p <- pnorm(abs(ctable_baseline_gender[, "t value"]), lower.tail = FALSE) * 2
## combined table
(ctable_baseline_gender <- cbind(ctable_baseline_gender, "p value" = baseline_gender_p))

#checking_assumptions

pid7_mapping <- c('Strong Democrat' = 1,
                  'Not Very Strong Democrat' = 2,
                  'Lean Democrat' = 3,
                  'Lean Republican' = 4,
                  'Not very Strong Republican' = 5,
                  'Strong Republican' = 6)

data_smol_dinan <- data_smol %>%
  mutate(pid7_num = as.numeric(recode_factor(pid7, !!!pid7_mapping)))


sf <- function(y) {
  c('Y>=1' = qlogis(mean(y >= 1)),
    'Y>=2' = qlogis(mean(y >= 2)),
    'Y>=3' = qlogis(mean(y >= 3)), 
    'Y>=4' = qlogis(mean(y >= 4)),
    'Y>=5' = qlogis(mean(y >= 5)))
}

#testing assumptions for gender baseline
gender_baseline <- with(data_smol_dinan, summary(as.numeric(pid7_num) ~ gender4, fun=sf))
plot(gender_baseline, which=1:5, pch=1:5, xlab='logit', main=' ', xlim=range(c(-3,3)))

```
```{r}
#gender and  with race model
race_gender_model<- polr(pid7 ~ gender4*race, data = data_smol, Hess=TRUE)
#store summary
summary_race_gender_model<-summary(race_gender_model)
# store table
(ctable_race_gender <- coef(summary(race_gender_model)))
## calculate and store p values
race_gender_p <- pnorm(abs(ctable_race_gender[, "t value"]), lower.tail = FALSE) * 2
## combined table
(ctable_race_gender <- cbind(ctable_race_gender, "p value" = race_gender_p))

#testing assumptions for gender + race
s_gender_race<- with(data_smol_dinan, summary(as.numeric(pid7_num) ~ gender4* race, fun=sf))

plot(s_gender_race, which=1:5, pch=1:5, xlab='logit', main=' ', xlim=range(c(-5,5)))

```
```{r}
#trying dinan's
#testing assumptions for region 
s <- with(data_smol_dinan, summary(as.numeric(pid7_num) ~ region, fun=sf))

plot(s, which=1:5, pch=1:5, xlab='logit', main=' ', xlim=range(c(-2,2)))

#testing assumptions for region + urbancity 
s_region_city<- with(data_smol_dinan, summary(as.numeric(pid7_num) ~ region + urbancity, fun=sf))

plot(s_region_city, which=1:5, pch=1:5, xlab='logit', main=' ', xlim=range(c(-2,2)))
```


DINAN SECTION

```{r}
 
#basic ordered logistic regression taking into account region
region_model<- polr(pid7 ~ region, data = data_smol, Hess=TRUE)
 
summary(region_model)

#basic ordered logistic regression taking into account region and urbancity 
region_urban_model<- polr(pid7 ~ region + urbancity, data = data_smol, Hess=TRUE)

summary(region_urban_model)

#checking_assumptions

pid7_mapping <- c('Strong Democrat' = 1,
                  'Not Very Strong Democrat' = 2,
                  'Lean Democrat' = 3,
                  'Lean Republican' = 4,
                  'Not very Strong Republican' = 5,
                  'Strong Republican' = 6)

data_smol_dinan <- data_smol %>%
  mutate(pid7_num = as.numeric(recode_factor(pid7, !!!pid7_mapping)))


sf <- function(y) {
  c('Y>=1' = qlogis(mean(y >= 1)),
    'Y>=2' = qlogis(mean(y >= 2)),
    'Y>=3' = qlogis(mean(y >= 3)), 
    'Y>=4' = qlogis(mean(y >= 4)),
    'Y>=5' = qlogis(mean(y >= 5)))
}

#testing assumptions for region 
s <- with(data_smol_dinan, summary(as.numeric(pid7_num) ~ region, fun=sf))

plot(s, which=1:3, pch=1:3, xlab='logit', main=' ', xlim=range(s[,3:4]))

#testing assumptions for region + urbancity 
s_region_city<- with(data_smol_dinan, summary(as.numeric(pid7_num) ~ region + urbancity, fun=sf))

plot(s_region_city, which=1:3, pch=1:3, xlab='logit', main=' ', xlim=range(s[,3:4]))

```

GRANT SECTION

```{r}

#religion 

religion_model <- polr(pid7 ~ religpew, data = data_smol, Hess=TRUE)

summary(religion_model)

# Extracting coefficient information
coef_summary <- summary(religion_model)$coef[1:11,]

# Names of the religions
religions <- sub("religpew", "", rownames(coef_summary))
coefficients <- as.numeric(coef_summary[, 1])
se <- as.numeric(coef_summary[, 2])

df <- data.frame(Religion = religions, Coefficient = coefficients, SE = se)

df$Religion <- reorder(df$Religion, df$Coefficient)

ggplot(df, aes(x = Coefficient, y = Religion)) +
  geom_point(size = 3, color = "blue", fill = "blue") +
  geom_errorbarh(aes(xmin = Coefficient - 2 * SE, xmax = Coefficient + 2 * SE), height = 0.2, color = "black") +
  labs(title = "Dot and Whisker Plot of Coefficients",
       x = "Coefficient Value") +
  theme_minimal()
```


```{r}
library(randomForest)

# Split the dataset into training and testing sets
set.seed(139) 
train_indices <- sample(1:nrow(data_smol), 0.7 * nrow(data_smol))  # 70% for training
train_data <- data_smol[train_indices, ]
test_data <- data_smol[-train_indices, ]

# Create a random forest model
rf_model <- randomForest(pid7 ~ ., data = train_data, ntree = 500, importance = TRUE)

# Extract variable importance from the random forest model
var_importance <- importance(rf_model)
print(var_importance)
varImpPlot(rf_model)

# Make predictions on the test set
predictions <- predict(rf_model, test_data)

# Evaluate the model
conf_matrix <- table(predictions, test_data$pid7)
print(conf_matrix)
accuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)
cat("Accuracy:", accuracy, "\n")
```